[workspace]
members = [
    "savant_core_py",
    "savant_python",
    "plugins/python/*",
    "plugins/native/*",
]

resolver = "2"

[workspace.package]
version = "0.2.11"
edition = "2021"
authors = ["Ivan Kudriavtsev <ivan.a.kudryavtsev@gmail.com>"]
description = "Savant Rust core functions library"
homepage = "https://github.com/insight-platform/savant-rs"
repository = "https://github.com/insight-platform/savant-rs"
readme = "README.md"
keywords = ["computer-vision", "video-processing"]
categories = ["algorithms", "data-structures", "computer-vision"]
license="Apache-2.0"
rust-version = "1.70"


[profile.release]
opt-level = 3
codegen-units = 1

[profile.bench]
opt-level = 3
codegen-units = 1

[workspace.dependencies]
savant_core = "0.2.13"