[package]
name = "savant_rs"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace =  true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
savant_core = { path = "../savant_core" }
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.11"
anyhow = "1.0"
thiserror = "1.0"
geo = "0.26"
rayon = "1.7"
pretty_env_logger = "0.5"
derive_builder = "0.12"
num_cpus = "1.15"
hashbrown = { version = "0.14", features = ["raw"]}
lazy_static = "1.4"
parking_lot = {version = "0.12", features = ["deadlock_detection"]}
evalexpr = { version = "11", features = ["rand", "regex_support"] }
log = "0.4"
opentelemetry = "0.19"
colored = "2"


[dependencies.pyo3]
version = "0.19"

[dev-dependencies]
serial_test = "2.0"

[build-dependencies]
pyo3-build-config = "0.19"
cbindgen = "0.24"

[package.metadata.maturin]
python-source = "python"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
