[package]
name = "savant_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.14", features = ["raw", "rkyv", "serde"]}
anyhow = "1"
geo = "0.26"
thiserror = "1"
lazy_static = "1.4"
crc32fast = "1"
opentelemetry = "0.19"
opentelemetry-jaeger = "0.18"
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
jmespath = { version = "0.3", features = ["sync"] }
lru = {version = "0.11", features = ["hashbrown"] }
evalexpr = { version = "11", features = ["rand", "regex_support"] }
parking_lot = {version = "0.12", features = ["deadlock_detection"]}
rkyv = { version = "0.7", features = ["validation", "archive_le"] }
etcd_dynamic_state = { path = "../etcd_dynamic_state" }
savant_utils = { path = "../savant_utils" }
derive_builder = "0.12"
rayon = "1.7"
libloading = "0.8"
log = "0.4"
uuid = {version = "1.4", features = ["fast-rng", "v4"]}

[dependencies.tokio]
version = "1.29"
features = ["rt-multi-thread"]

[lib]
crate-type = ["cdylib", "lib"]