[package]
name = "savant_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytes = "1.5"
crc32fast = "1"
crossbeam = "0.8"
derive_builder = "0.13"
evalexpr = { version = "11", features = ["rand", "regex_support"] }
etcd_dynamic_state = { git = "https://github.com/insight-platform/etcd_dynamic_state", tag = "0.2.11" }
geo = "0.26"
hashbrown = { version = "0.14", features = ["raw", "serde"] }
jmespath = { version = "0.3", features = ["sync"] }
lazy_static = "1.4"
libloading = "0.8"
log = "0.4"
lru = { version = "0.12", features = ["hashbrown"] }
mini-moka = "0.10"
opentelemetry = "0.21"
opentelemetry_sdk = "0.21"
opentelemetry-stdout = { version = "0.2", features = ["trace"] }
opentelemetry-jaeger = "0.20"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
prost = "0.12"
prost-types = "0.12"
rayon = "1.8"
regex = "1"
savant-protobuf = { git = "https://github.com/insight-platform/savant-protobuf", tag = "0.2.0" }

serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
uuid = { version = "1.7", features = ["fast-rng", "v7"] }
zmq = "0.10"
rand = "0.8.5"

[dependencies.tokio]
version = "1.35"
features = ["rt-multi-thread"]


[lib]
crate-type = ["dylib"]

[[bin]]
name = "plugin-loader"
path = "src/bin/plugin_loader.rs"
